-- Conteos por tabla de sports. Correr conectado a la base 'sports'.
-- Igual en ambos dialectos.
SELECT 'addresses' AS tabla, COUNT(*) AS filas FROM addresses
UNION ALL SELECT 'affiliation_phases' AS tabla, COUNT(*) AS filas FROM affiliation_phases
UNION ALL SELECT 'affiliations' AS tabla, COUNT(*) AS filas FROM affiliations
UNION ALL SELECT 'affiliations_documents' AS tabla, COUNT(*) AS filas FROM affiliations_documents
UNION ALL SELECT 'affiliations_events' AS tabla, COUNT(*) AS filas FROM affiliations_events
UNION ALL SELECT 'affiliations_media' AS tabla, COUNT(*) AS filas FROM affiliations_media
UNION ALL SELECT 'american_football_action_participants' AS tabla, COUNT(*) AS filas FROM american_football_action_participants
UNION ALL SELECT 'american_football_action_plays' AS tabla, COUNT(*) AS filas FROM american_football_action_plays
UNION ALL SELECT 'american_football_defensive_stats' AS tabla, COUNT(*) AS filas FROM american_football_defensive_stats
UNION ALL SELECT 'american_football_down_progress_stats' AS tabla, COUNT(*) AS filas FROM american_football_down_progress_stats
UNION ALL SELECT 'american_football_event_states' AS tabla, COUNT(*) AS filas FROM american_football_event_states
UNION ALL SELECT 'american_football_fumbles_stats' AS tabla, COUNT(*) AS filas FROM american_football_fumbles_stats
UNION ALL SELECT 'american_football_offensive_stats' AS tabla, COUNT(*) AS filas FROM american_football_offensive_stats
UNION ALL SELECT 'american_football_passing_stats' AS tabla, COUNT(*) AS filas FROM american_football_passing_stats
UNION ALL SELECT 'american_football_penalties_stats' AS tabla, COUNT(*) AS filas FROM american_football_penalties_stats
UNION ALL SELECT 'american_football_rushing_stats' AS tabla, COUNT(*) AS filas FROM american_football_rushing_stats
UNION ALL SELECT 'american_football_sacks_against_stats' AS tabla, COUNT(*) AS filas FROM american_football_sacks_against_stats
UNION ALL SELECT 'american_football_scoring_stats' AS tabla, COUNT(*) AS filas FROM american_football_scoring_stats
UNION ALL SELECT 'american_football_special_teams_stats' AS tabla, COUNT(*) AS filas FROM american_football_special_teams_stats
UNION ALL SELECT 'baseball_action_contact_details' AS tabla, COUNT(*) AS filas FROM baseball_action_contact_details
UNION ALL SELECT 'baseball_action_pitches' AS tabla, COUNT(*) AS filas FROM baseball_action_pitches
UNION ALL SELECT 'baseball_action_plays' AS tabla, COUNT(*) AS filas FROM baseball_action_plays
UNION ALL SELECT 'baseball_action_substitutions' AS tabla, COUNT(*) AS filas FROM baseball_action_substitutions
UNION ALL SELECT 'baseball_defensive_group' AS tabla, COUNT(*) AS filas FROM baseball_defensive_group
UNION ALL SELECT 'baseball_defensive_players' AS tabla, COUNT(*) AS filas FROM baseball_defensive_players
UNION ALL SELECT 'baseball_defensive_stats' AS tabla, COUNT(*) AS filas FROM baseball_defensive_stats
UNION ALL SELECT 'baseball_event_states' AS tabla, COUNT(*) AS filas FROM baseball_event_states
UNION ALL SELECT 'baseball_offensive_stats' AS tabla, COUNT(*) AS filas FROM baseball_offensive_stats
UNION ALL SELECT 'baseball_pitching_stats' AS tabla, COUNT(*) AS filas FROM baseball_pitching_stats
UNION ALL SELECT 'basketball_defensive_stats' AS tabla, COUNT(*) AS filas FROM basketball_defensive_stats
UNION ALL SELECT 'basketball_event_states' AS tabla, COUNT(*) AS filas FROM basketball_event_states
UNION ALL SELECT 'basketball_offensive_stats' AS tabla, COUNT(*) AS filas FROM basketball_offensive_stats
UNION ALL SELECT 'basketball_rebounding_stats' AS tabla, COUNT(*) AS filas FROM basketball_rebounding_stats
UNION ALL SELECT 'basketball_team_stats' AS tabla, COUNT(*) AS filas FROM basketball_team_stats
UNION ALL SELECT 'bookmakers' AS tabla, COUNT(*) AS filas FROM bookmakers
UNION ALL SELECT 'core_person_stats' AS tabla, COUNT(*) AS filas FROM core_person_stats
UNION ALL SELECT 'core_stats' AS tabla, COUNT(*) AS filas FROM core_stats
UNION ALL SELECT 'db_info' AS tabla, COUNT(*) AS filas FROM db_info
UNION ALL SELECT 'display_names' AS tabla, COUNT(*) AS filas FROM display_names
UNION ALL SELECT 'document_classes' AS tabla, COUNT(*) AS filas FROM document_classes
UNION ALL SELECT 'document_contents' AS tabla, COUNT(*) AS filas FROM document_contents
UNION ALL SELECT 'document_fixtures' AS tabla, COUNT(*) AS filas FROM document_fixtures
UNION ALL SELECT 'document_fixtures_events' AS tabla, COUNT(*) AS filas FROM document_fixtures_events
UNION ALL SELECT 'document_package_entry' AS tabla, COUNT(*) AS filas FROM document_package_entry
UNION ALL SELECT 'document_packages' AS tabla, COUNT(*) AS filas FROM document_packages
UNION ALL SELECT 'documents' AS tabla, COUNT(*) AS filas FROM documents
UNION ALL SELECT 'documents_media' AS tabla, COUNT(*) AS filas FROM documents_media
UNION ALL SELECT 'events' AS tabla, COUNT(*) AS filas FROM events
UNION ALL SELECT 'events_documents' AS tabla, COUNT(*) AS filas FROM events_documents
UNION ALL SELECT 'events_media' AS tabla, COUNT(*) AS filas FROM events_media
UNION ALL SELECT 'events_sub_seasons' AS tabla, COUNT(*) AS filas FROM events_sub_seasons
UNION ALL SELECT 'ice_hockey_action_participants' AS tabla, COUNT(*) AS filas FROM ice_hockey_action_participants
UNION ALL SELECT 'ice_hockey_action_plays' AS tabla, COUNT(*) AS filas FROM ice_hockey_action_plays
UNION ALL SELECT 'ice_hockey_defensive_stats' AS tabla, COUNT(*) AS filas FROM ice_hockey_defensive_stats
UNION ALL SELECT 'ice_hockey_event_states' AS tabla, COUNT(*) AS filas FROM ice_hockey_event_states
UNION ALL SELECT 'ice_hockey_offensive_stats' AS tabla, COUNT(*) AS filas FROM ice_hockey_offensive_stats
UNION ALL SELECT 'ice_hockey_player_stats' AS tabla, COUNT(*) AS filas FROM ice_hockey_player_stats
UNION ALL SELECT 'injury_phases' AS tabla, COUNT(*) AS filas FROM injury_phases
UNION ALL SELECT 'key_aliases' AS tabla, COUNT(*) AS filas FROM key_aliases
UNION ALL SELECT 'key_roots' AS tabla, COUNT(*) AS filas FROM key_roots
UNION ALL SELECT 'latest_revisions' AS tabla, COUNT(*) AS filas FROM latest_revisions
UNION ALL SELECT 'locations' AS tabla, COUNT(*) AS filas FROM locations
UNION ALL SELECT 'media' AS tabla, COUNT(*) AS filas FROM media
UNION ALL SELECT 'media_captions' AS tabla, COUNT(*) AS filas FROM media_captions
UNION ALL SELECT 'media_contents' AS tabla, COUNT(*) AS filas FROM media_contents
UNION ALL SELECT 'media_keywords' AS tabla, COUNT(*) AS filas FROM media_keywords
UNION ALL SELECT 'motor_racing_event_states' AS tabla, COUNT(*) AS filas FROM motor_racing_event_states
UNION ALL SELECT 'motor_racing_qualifying_stats' AS tabla, COUNT(*) AS filas FROM motor_racing_qualifying_stats
UNION ALL SELECT 'motor_racing_race_stats' AS tabla, COUNT(*) AS filas FROM motor_racing_race_stats
UNION ALL SELECT 'outcome_totals' AS tabla, COUNT(*) AS filas FROM outcome_totals
UNION ALL SELECT 'participants_events' AS tabla, COUNT(*) AS filas FROM participants_events
UNION ALL SELECT 'periods' AS tabla, COUNT(*) AS filas FROM periods
UNION ALL SELECT 'person_event_metadata' AS tabla, COUNT(*) AS filas FROM person_event_metadata
UNION ALL SELECT 'person_phases' AS tabla, COUNT(*) AS filas FROM person_phases
UNION ALL SELECT 'persons' AS tabla, COUNT(*) AS filas FROM persons
UNION ALL SELECT 'persons_documents' AS tabla, COUNT(*) AS filas FROM persons_documents
UNION ALL SELECT 'persons_media' AS tabla, COUNT(*) AS filas FROM persons_media
UNION ALL SELECT 'positions' AS tabla, COUNT(*) AS filas FROM positions
UNION ALL SELECT 'publishers' AS tabla, COUNT(*) AS filas FROM publishers
UNION ALL SELECT 'roles' AS tabla, COUNT(*) AS filas FROM roles
UNION ALL SELECT 'seasons' AS tabla, COUNT(*) AS filas FROM seasons
UNION ALL SELECT 'sites' AS tabla, COUNT(*) AS filas FROM sites
UNION ALL SELECT 'soccer_defensive_stats' AS tabla, COUNT(*) AS filas FROM soccer_defensive_stats
UNION ALL SELECT 'soccer_event_states' AS tabla, COUNT(*) AS filas FROM soccer_event_states
UNION ALL SELECT 'soccer_foul_stats' AS tabla, COUNT(*) AS filas FROM soccer_foul_stats
UNION ALL SELECT 'soccer_offensive_stats' AS tabla, COUNT(*) AS filas FROM soccer_offensive_stats
UNION ALL SELECT 'standing_subgroups' AS tabla, COUNT(*) AS filas FROM standing_subgroups
UNION ALL SELECT 'standings' AS tabla, COUNT(*) AS filas FROM standings
UNION ALL SELECT 'stats' AS tabla, COUNT(*) AS filas FROM stats
UNION ALL SELECT 'sub_periods' AS tabla, COUNT(*) AS filas FROM sub_periods
UNION ALL SELECT 'sub_seasons' AS tabla, COUNT(*) AS filas FROM sub_seasons
UNION ALL SELECT 'team_american_football_stats' AS tabla, COUNT(*) AS filas FROM team_american_football_stats
UNION ALL SELECT 'team_phases' AS tabla, COUNT(*) AS filas FROM team_phases
UNION ALL SELECT 'teams' AS tabla, COUNT(*) AS filas FROM teams
UNION ALL SELECT 'teams_documents' AS tabla, COUNT(*) AS filas FROM teams_documents
UNION ALL SELECT 'teams_media' AS tabla, COUNT(*) AS filas FROM teams_media
UNION ALL SELECT 'tennis_action_points' AS tabla, COUNT(*) AS filas FROM tennis_action_points
UNION ALL SELECT 'tennis_action_volleys' AS tabla, COUNT(*) AS filas FROM tennis_action_volleys
UNION ALL SELECT 'tennis_event_states' AS tabla, COUNT(*) AS filas FROM tennis_event_states
UNION ALL SELECT 'tennis_return_stats' AS tabla, COUNT(*) AS filas FROM tennis_return_stats
UNION ALL SELECT 'tennis_service_stats' AS tabla, COUNT(*) AS filas FROM tennis_service_stats
UNION ALL SELECT 'wagering_moneylines' AS tabla, COUNT(*) AS filas FROM wagering_moneylines
UNION ALL SELECT 'wagering_odds_lines' AS tabla, COUNT(*) AS filas FROM wagering_odds_lines
UNION ALL SELECT 'wagering_runlines' AS tabla, COUNT(*) AS filas FROM wagering_runlines
UNION ALL SELECT 'wagering_straight_spread_lines' AS tabla, COUNT(*) AS filas FROM wagering_straight_spread_lines
UNION ALL SELECT 'wagering_total_score_lines' AS tabla, COUNT(*) AS filas FROM wagering_total_score_lines
UNION ALL SELECT 'weather_conditions' AS tabla, COUNT(*) AS filas FROM weather_conditions
ORDER BY tabla;
